export default {
    API_VERSION: process.env.API_VERSION,
    BASE_URL: `/api/${process.env.API_VERSION}`,
    NODE_ENV: process.env.NODE_ENV || "development",
    HOST: process.env.HOST || "localhost",
    PORT: process.env.PORT || 3000,
    SMS_APP_HOST: process.env.SMS_APP_HOST || "localhost",
    SMS_APP_PORT: process.env.SMS_APP_PORT || 80,
    PUSH_APP_HOST: process.env.PUSH_APP_HOST || "localhost",
    PUSH_APP_PORT: process.env.PUSH_APP_PORT || 80,
    FILE_APP_HOST: process.env.FILE_APP_HOST || "localhost",
    FILE_APP_PORT: process.env.FILE_APP_PORT || 80,
    SMS_TEXT: process.env.SMS_TEXT || "{{ code }} - YOUHIRE confirmation code",
    TIME_TO_ACCEPT: 120000,
    AVERAGE_TIME_OF_EXECUTION: 15 * 60 * 1000,
    COMMISSION: 0.2,
    CODE_LEN: process.env.CODE_LEN || 6,
    CODE_PERIOD: process.env.CODE_PERIOD || 5,
    JWT_SECRET: process.env.JWT_SECRET || "1234567890",
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY || "AIzaSyAx6BpFSVWVZ8UYvt1RvoH6IcJn0smMdwE",
    STRIPE_API_KEY: process.env.STRIPE_API_KEY || "sk_test_dwHcFtAgdpwyMM3iprU5YCbJ",
    PG_HOST: process.env.PG_HOST || "localhost",
    PG_PORT: process.env.PG_PORT || 5432,
    PG_USER: process.env.PG_USER || "admin",
    PG_PASSWORD: process.env.PG_PASSWORD || "12345678",
    PG_DB: process.env.PG_DB || "youhire_db"
}
